//
//  DataFile.swift
//  EKBTransport
//
//  Created by Артем Галиев on 09.04.2020.
//  Copyright © 2020 Артем Галиев. All rights reserved.
//

class TransportData {
    static let dataTram: [Transport] =
        [Transport(link: "https://mobile.ettu.ru/station/1168", nameStation: "1-й км (на Пионерскую)", secondName: "1-й км", searchName: "Первый километр"),
         Transport(link: "https://mobile.ettu.ru/station/1169", nameStation: "1-й км (на Техучилище)", secondName: "1-й км", searchName: "Первый километр"),
         Transport(link: "https://mobile.ettu.ru/station/3497", nameStation: "40 лет ВЛКСМ", secondName: "40 лет ВЛКСМ", searchName: "Сорок лет ВЛКСМ"),
         Transport(link: "https://mobile.ettu.ru/station/1170", nameStation: "40 лет Октября (на Диагностический центр)", secondName: "40 лет Октября", searchName: "Сорок лет Октября"),
         Transport(link: "https://mobile.ettu.ru/station/1171", nameStation: "40 лет Октября (на ст. Машиностроителей)", secondName: "40 лет Октября", searchName: "Сорок лет Октября"),
         Transport(link: "https://mobile.ettu.ru/station/3498", nameStation: "7 Ключей", secondName: "7 Ключей", searchName: "Семь Ключей"),
         Transport(link: "https://mobile.ettu.ru/station/4007", nameStation: "Автовокзал (на Фрунзе)", secondName: "Автовокзал", searchName: "Автовокзал"),
         Transport(link: "https://mobile.ettu.ru/station/4008", nameStation: "Автовокзал (на Южную)", secondName: "Автовокзал", searchName: "Автовокзал"),
         Transport(link: "https://mobile.ettu.ru/station/3316", nameStation: "Автомагистральная (на Пехотинцев)", secondName: "Автомагистральная", searchName: "Автомагистральная"),
         Transport(link: "https://mobile.ettu.ru/station/3317", nameStation: "Автомагистральная (на Сварщиков)", secondName: "Автомагистральная", searchName: "Автомагистральная"),
         Transport(link: "https://mobile.ettu.ru/station/3362", nameStation: "Академия при Президенте России (на Большакова)", secondName: "Академия при Пр. РФ", searchName: "Академия при Пр. РФ"),
         Transport(link: "https://mobile.ettu.ru/station/3363", nameStation: "Академия при Президенте России (на Цирк)", secondName: "Академия при Пр. РФ", searchName: "Академия при Пр. РФ"),
         Transport(link: "https://mobile.ettu.ru/station/3819", nameStation: "Бажова (на Восточную)", secondName: "Бажова", searchName: "Бажова"),
         Transport(link: "https://mobile.ettu.ru/station/3825", nameStation: "Бажова (на гост. Исеть, Оперный театр, Дом Кино)", secondName: "Бажова", searchName: "Бажова"),
         Transport(link: "https://mobile.ettu.ru/station/3436", nameStation: "Бакинских Комиссаров (на Уральских Рабочих)", secondName: "Бакинских Комиссаров", searchName: "Бакинских Комиссаров"),
         Transport(link: "https://mobile.ettu.ru/station/3437", nameStation: "Бакинских Комиссаров (на Победы)", secondName: "Бакинских Комиссаров", searchName: "Бакинских Комиссаров"),
         Transport(link: "https://mobile.ettu.ru/station/4369", nameStation: "Бебеля (на Пехотинцев)", secondName: "Бебеля", searchName: "Бебеля"),
         Transport(link: "https://mobile.ettu.ru/station/4370", nameStation: "Бебеля (на Таганский ряд)", secondName: "Бебеля", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3320", nameStation: "Белинского (на Дом художника)", secondName: "Белинского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3321", nameStation: "Белинского (на Цирк)", secondName: "Белинского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3322", nameStation: "Белореченская (на Волгоградскую)", secondName: "Белореченская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3323", nameStation: "Белореченская (на Московскую)", secondName: "Белореченская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4162", nameStation: "Библиотека (на Донбасскую)", secondName: "Библиотека", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4173", nameStation: "Библиотека (на Лукиных)", secondName: "Библиотека", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3324", nameStation: "Блюхера (на ст.Шарташ)", secondName: "Блюхера", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3325", nameStation: "Блюхера (с Мира на Уральский федеральный университет)", secondName: "Блюхера", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3326", nameStation: "Блюхера (с Советской на Уральский федеральный университет)", secondName: "Блюхера", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3327", nameStation: "Блюхера (на Пионерскую)", secondName: "Блюхера", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3328", nameStation: "Большакова (на Академию при Президенте России)", secondName: "Большакова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3329", nameStation: "Большакова (на Фрунзе)", secondName: "Большакова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963627", nameStation: "Б-р Малахова (на Фучика)", secondName: "Б-р Малахова", searchName: "Малахова"),
         Transport(link: "https://mobile.ettu.ru/station/963630", nameStation: "Б-р Малахова (на ст. м. Ботаническая)", secondName: "Б-р Малахова", searchName: "Малахова"),
         Transport(link: "https://mobile.ettu.ru/station/4307", nameStation: "Братская (на Сухоложскую)", secondName: "Братская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4308", nameStation: "Братская (на Завод РТИ)", secondName: "Братская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4276", nameStation: "Ватутина (на ст. 7 Ключей)", secondName: "Ватутина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4279", nameStation: "Ватутина (на Таганский ряд)", secondName: "Ватутина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3332", nameStation: "Верх-Исетский б-р (на Крылова)", secondName: "Верх-Исетский б-р", searchName: "Верх Исетский б-р"),
         Transport(link: "https://mobile.ettu.ru/station/3333", nameStation: "Верх-Исетский б-р (на Дворец Молодежи)", secondName: "Верх-Исетский б-р", searchName: "Верх Исетский б-р"),
         Transport(link: "https://mobile.ettu.ru/station/4118", nameStation: "Верх-Исетский рынок (на Таганский ряд)", secondName: "Верх-Исетский рынок", searchName: "Верх Исетский рынок"),
         Transport(link: "https://mobile.ettu.ru/station/4119", nameStation: "Верх-Исетский рынок (на Колмогорова)", secondName: "Верх-Исетский рынок", searchName: "Верх Исетский рынок"),
         Transport(link: "https://mobile.ettu.ru/station/963737", nameStation: "Вечный Огонь (на Мельникова)", secondName: "Вечный Огонь", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963738", nameStation: "Вечный Огонь (на пл. Коммунаров)", secondName: "Вечный Огонь", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3499", nameStation: "ВИЗ", secondName: "ВИЗ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3336", nameStation: "Викулова (на Волгоградскую)", secondName: "Викулова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3337", nameStation: "Викулова (на ст. ВИЗ)", secondName: "Викулова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3338", nameStation: "Войкова (на ст. Фрезеровщиков)", secondName: "Войкова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3339", nameStation: "Войкова (на Энтузиастов)", secondName: "Войкова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3495", nameStation: "Волгоградская", secondName: "Волгоградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961847", nameStation: "Волгоградская (на ТК Буревестник)", secondName: "Волгоградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961848", nameStation: "Волгоградская (на Серафимы Дерябиной)", secondName: "Волгоградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3344", nameStation: "Ворошиловская (на Фронтовых Бригад)", secondName: "Ворошиловская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3345", nameStation: "Ворошиловская (на Электриков)", secondName: "Ворошиловская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3820", nameStation: "Восточная (на Уральский федеральный университет)", secondName: "Восточная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3823", nameStation: "Восточная (на Бажова)", secondName: "Восточная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4269", nameStation: "Вторчермет", secondName: "Вторчермет", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3350", nameStation: "Гагарина (на Профессорскую)", secondName: "Гагарина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3351", nameStation: "Гагарина (на Уральский федеральный университет)", secondName: "УрФУ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3348", nameStation: "Гост. Исеть (на Шарташскую)", secondName: "Гост. Исеть", searchName: "Гостинеца Исеть"),
         Transport(link: "https://mobile.ettu.ru/station/3349", nameStation: "Гост. Исеть (на Бажова, Дом Кино, Оперный театр)", secondName: "Гост. Исеть", searchName: "Гостинеца Исеть"),
         Transport(link: "https://mobile.ettu.ru/station/3352", nameStation: "Гурзуфская (на Волгоградскую)", secondName: "Гурзуфская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3353", nameStation: "Гурзуфская (на Московскую)", secondName: "Гурзуфская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3361", nameStation: "Дворец Молодежи (на Верх-Исетский б-р)", secondName: "Дворец Молодежи", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963743", nameStation: "Дворец Молодежи (на пл.Коммунаров, Шейнкмана)", secondName: "Дворец Молодежи", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3360", nameStation: "Дворец Спорта", secondName: "Дворец Спорта", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3364", nameStation: "Декабристов (на Дом художника)", secondName: "Декабристов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3365", nameStation: "Декабристов (на пл. Обороны)", secondName: "Декабристов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3314", nameStation: "Диагностический центр (на 40 лет Октября)", secondName: "Диагностический центр", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3315", nameStation: "Диагностический центр (на Лукиных)", secondName: "Диагностический центр", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4272", nameStation: "ДК ВОС (на ст. 7 Ключей)", secondName: "ДК ВОС", searchName: "Дворец культуры ВОС"),
         Transport(link: "https://mobile.ettu.ru/station/4275", nameStation: "ДК ВОС (на Таганский ряд)", secondName: "ДК ВОС", searchName: "Дворец культуры ВОС"),
         Transport(link: "https://mobile.ettu.ru/station/3354", nameStation: "ДК им. Лаврова (на Ильича)", secondName: "ДК им. Лаврова", searchName: "Дворец Культуры имени Лаврова"),
         Transport(link: "https://mobile.ettu.ru/station/3355", nameStation: "ДК им. Лаврова (на Кузнецова)", secondName: "ДК им. Лаврова", searchName: "Дворец Культуры имени Лаврова"),
         Transport(link: "https://mobile.ettu.ru/station/3366", nameStation: "Дом Кино (на Киностудию)", secondName: "Дом Кино", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3367", nameStation: "Дом Кино (на Дом художника)", secondName: "Дом Кино", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3396", nameStation: "Дом художника (на Дом Кино)", secondName: "Дом художника", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3397", nameStation: "Дом художника (на Декабристов)", secondName: "Дом художника", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3398", nameStation: "Дом художника (с Декабристов на Цирк)", secondName: "Дом художника", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3399", nameStation: "Дом художника (с Дома Кино на Цирк)", secondName: "Дом художника", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4163", nameStation: "Донбасская (на Кировградскую)", secondName: "Донбасская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4172", nameStation: "Донбасская (на Библиотеку)", secondName: "Донбасская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3736", nameStation: "Донская (на ст. Эльмаш)", secondName: "Донская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4238", nameStation: "Донская (на Энтузиастов)", secondName: "Донская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4286", nameStation: "Дружининская (на Таганский ряд)", secondName: "Дружининская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4287", nameStation: "Дружининская (на ст. 7 Ключей)", secondName: "Дружининская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/1172", nameStation: "Ельцина (на Управление дороги)", secondName: "Ельцина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/1173", nameStation: "Ельцина (на Папанина)", secondName: "Ельцина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3340", nameStation: "Ж/д вокзал (на Управление дороги)", secondName: "Ж/д вокзал", searchName: "Жд вокзал"),
         Transport(link: "https://mobile.ettu.ru/station/3341", nameStation: "Ж/д вокзал (на Челюскинцев, Пионерскую)", secondName: "Ж/д вокзал", searchName: "Жд вокзал"),
         Transport(link: "https://mobile.ettu.ru/station/4025", nameStation: "Завод РТИ (на Братскую)", secondName: "Завод РТИ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4026", nameStation: "Завод РТИ (на пер. Рижский)", secondName: "Завод РТИ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3368", nameStation: "Заводская (на Красноуральскую)", secondName: "Заводская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3369", nameStation: "Заводская (на Татищева)", secondName: "Заводская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4062", nameStation: "Зеленый остров", secondName: "Зеленый остров", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3370", nameStation: "Ильича (на ДК им. Лаврова)", secondName: "Ильича", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3371", nameStation: "Ильича (на Индустрии)", secondName: "Ильича", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3372", nameStation: "Индустрии (на Ильича)", secondName: "Индустрии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3373", nameStation: "Индустрии (на Победы)", secondName: "Индустрии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3378", nameStation: "Калининская (на Педагогический университет)", secondName: "Калининская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3379", nameStation: "Калининская (на Техучилище)", secondName: "Калининская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3380", nameStation: "Каменные Палатки (на Комсомольскую)", secondName: "Каменные Палатки", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3381", nameStation: "Каменные Палатки (на Новгородцевой)", secondName: "Каменные Палатки", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4268", nameStation: "Керамическая", secondName: "Керамическая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3382", nameStation: "Киностудия (на Бажова, гост. Исеть, Оперный театр)", secondName: "Киностудия", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3702", nameStation: "Кирова (на Крылова)", secondName: "Кирова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3960", nameStation: "Кирова (на ст. ВИЗ)", secondName: "Кирова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4107", nameStation: "Кирова (на Колмогорова)", secondName: "Кирова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3383", nameStation: "Кировградская (на Донбасскую)", secondName: "Кировградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3384", nameStation: "Кировградская (на Уральских Рабочих)", secondName: "Кировградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4284", nameStation: "Кишиневская (на Таганский ряд)", secondName: "Кишиневская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4285", nameStation: "Кишиневская (на ст. 7 Ключей)", secondName: "Кишиневская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3386", nameStation: "Колмогорова (на Таганский ряд)", secondName: "Колмогорова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4117", nameStation: "Колмогорова (на Кирова)", secondName: "Колмогорова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3387", nameStation: "Комсомольская (на Профессорскую)", secondName: "Комсомольская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3388", nameStation: "Комсомольская (на ст. 40 лет ВЛКСМ)", secondName: "Комсомольская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3529", nameStation: "Кондукторская (на Пионерскую)", secondName: "Кондукторская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3535", nameStation: "Кондукторская (на Блюхера)", secondName: "Кондукторская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963721", nameStation: "Красноуральская (на Заводскую)", secondName: "Красноуральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963724", nameStation: "Красноуральская (на Слесарей)", secondName: "Красноуральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963728", nameStation: "Красноуральская (на Уралкабель)", secondName: "Красноуральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3389", nameStation: "Краснофлотцев (на Фронтовых Бригад)", secondName: "Краснофлотцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3390", nameStation: "Краснофлотцев (на Энтузиастов)", secondName: "Краснофлотцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3391", nameStation: "Крылова (на Верх-Исетский б-р)", secondName: "Крылова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3392", nameStation: "Крылова (на Кирова)", secondName: "Крылова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3393", nameStation: "Кузнецова (с ДК им. Лаврова на ст. пл. 1-й Пятилетки)", secondName: "Кузнецова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3394", nameStation: "Кузнецова (с м. Уралмаш на ст. пл. 1-й Пятилетки)", secondName: "Кузнецова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3395", nameStation: "Кузнецова (на ДК им. Лаврова)", secondName: "Кузнецова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961839", nameStation: "Кузнецова (на м. Уралмаш)", secondName: "Кузнецова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961849", nameStation: "Куйбышева (на Цирк, пл. Коммунаров)", secondName: "Куйбышева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961850", nameStation: "Куйбышева (на ст. Дворец Спорта)", secondName: "Куйбышева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963233", nameStation: "Кушвинская", secondName: "Кушвинская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3400", nameStation: "Лукиных (на  Библиотеку)", secondName: "Лукиных", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3401", nameStation: "Лукиных (на Диагностический центр)", secondName: "Лукиных", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3402", nameStation: "Лукиных (на Сварщиков)", secondName: "Лукиных", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4353", nameStation: "Ляпустина (на ст. Керамическая)", secondName: "Ляпустина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4354", nameStation: "Ляпустина (на Ферганскую)", secondName: "Ляпустина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963621", nameStation: "Метро Ботаническая", secondName: "М. Ботаническая", searchName: "Ботаническая"),
         Transport(link: "https://mobile.ettu.ru/station/3405", nameStation: "Метро Уралмаш (на Кузнецова)", secondName: "М. Уралмаш", searchName: "Уралмаш"),
         Transport(link: "https://mobile.ettu.ru/station/3406", nameStation: "Метро Уралмаш (на Педагогический университет)", secondName: "М. Уралмаш", searchName: "Уралмаш"),
         Transport(link: "https://mobile.ettu.ru/station/4057", nameStation: "Малый конный (на ст. Зеленый остров)", secondName: "Малый конный", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4064", nameStation: "Малый конный (на ст. ВИЗ)", secondName: "Малый конный", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4278", nameStation: "Маневровая (на ст. 7 Ключей)", secondName: "Маневровая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4301", nameStation: "Маневровая (на Таганский ряд)", secondName: "Маневровая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3500", nameStation: "Машиностроителей", secondName: "Машиностроителей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963733", nameStation: "Мельникова (на Уралкабель)", secondName: "Мельникова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963734", nameStation: "Мельникова (на Вечный Огонь)", secondName: "Мельникова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4045", nameStation: "Металлургов (на ст. ВИЗ)", secondName: "Металлургов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4046", nameStation: "Металлургов (на Волгоградскую)", secondName: "Металлургов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3407", nameStation: "Мира (на Блюхера)", secondName: "Мира", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3408", nameStation: "Мира (на ТК Современник)", secondName: "Мира", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3409", nameStation: "Московская (на ст. Дворец Спорта)", secondName: "Московская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3410", nameStation: "Московская (на ТК Алатырь)", secondName: "Московская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3411", nameStation: "Московская (на Юго-Западную)", secondName: "Московская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3412", nameStation: "Московская (с ТК Алатырь на Цирк)", secondName: "Московская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961866", nameStation: "Московская (с Юго-Западной на Цирк)", secondName: "Московская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963698", nameStation: "Московская от ст. Дворец Спорта (со ст. Дворец Спорта на Цирк)", secondName: "Московская от ст. ДС", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4349", nameStation: "Мусоргского (на ст. Керамическая)", secondName: "Мусоргского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4350", nameStation: "Мусоргского (на Эскадронную)", secondName: "Мусоргского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3414", nameStation: "Новгородцевой (на Каменные палатки)", secondName: "Новгородцевой", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3415", nameStation: "Новгородцевой (на Сиреневый б-р)", secondName: "Новгородцевой", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961851", nameStation: "Новомосковская (на ст. ВИЗ)", secondName: "Новомосковская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961852", nameStation: "Новомосковская (на Волгоградскую)", secondName: "Новомосковская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4347", nameStation: "Новосибирская (на ст. Керамическая)", secondName: "Новосибирская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4348", nameStation: "Новосибирская (на Ляпустина)", secondName: "Новосибирская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3416", nameStation: "Оперный театр (на пл. 1905 года)", secondName: "Оперный театр", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3417", nameStation: "Оперный театр (на гост. Исеть, Бажова,  Дом Кино)", secondName: "Оперный театр", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3418", nameStation: "Папанина (на Шейнкмана)", secondName: "Папанина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3419", nameStation: "Папанина (на Управление дороги)", secondName: "Папанина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3420", nameStation: "Педагогический университет (на м. Уралмаш)", secondName: "Педагогический университет", searchName: "Пед университет"),
         Transport(link: "https://mobile.ettu.ru/station/3421", nameStation: "Педагогический университет (на Пионерскую)", secondName: "Педагогический университет", searchName: "Пед университет"),
         Transport(link: "https://mobile.ettu.ru/station/3422", nameStation: "Педагогический университет (на Электриков)", secondName: "Педагогический университет", searchName: "Пед университет"),
         Transport(link: "https://mobile.ettu.ru/station/3423", nameStation: "Педагогический университет (с Электриков на Пионерскую)", secondName: "Педагогический университет", searchName: "Пед университет"),
         Transport(link: "https://mobile.ettu.ru/station/3356", nameStation: "Пер. Рижский (на Завод РТИ)", secondName: "Пер. Рижский", searchName: "Переулок Рижевский"),
         Transport(link: "https://mobile.ettu.ru/station/3357", nameStation: "Пер. Рижский (на Ювелирную)", secondName: "Пер. Рижский", searchName: "Переулок Рижевский"),
         Transport(link: "https://mobile.ettu.ru/station/3424", nameStation: "Первомайская (на Блюхера)", secondName: "Первомайская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3425", nameStation: "Первомайская (на Уральский федеральный университет)", secondName: "Первомайская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4134", nameStation: "Пехотинцев (на Автомагистральную)", secondName: "Пехотинцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4367", nameStation: "Пехотинцев (на Бебеля)", secondName: "Пехотинцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3426", nameStation: "Пионерская (на 1-й км)", secondName: "Пионерская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3428", nameStation: "Пионерская (с 1-го км на Челюскинцев, Ж/д вокзал)", secondName: "Пионерская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3429", nameStation: "Пионерская (с Кондукторской на Челюскинцев, Ж/д вокзал)", secondName: "Пионерская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4192", nameStation: "Пионерская (на Кондукторскую)", secondName: "Пионерская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3430", nameStation: "Пл. 1905 г. (на гост. Исеть)", secondName: "Пл. 1905 г", searchName: "Площадь 1905"),
         Transport(link: "https://mobile.ettu.ru/station/3431", nameStation: "Пл. 1905 г. (на пл. Коммунаров)", secondName: "Пл. 1905 г", searchName: "Площадь 1905"),
         Transport(link: "https://mobile.ettu.ru/station/3501", nameStation: "Пл. 1-й Пятилетки", secondName: "Пл. 1-й Пятилетки", searchName: "Площадь первой Пятилетки"),
         Transport(link: "https://mobile.ettu.ru/station/963149", nameStation: "Пл. 1-й Пятилетки (на ст. пл. 1-й Пятилетки)", secondName: "Пл. 1-й Пятилетки", searchName: "Площадь первой Пятилетки"),
         Transport(link: "https://mobile.ettu.ru/station/3432", nameStation: "Пл. Коммунаров (на ТК Алатырь)", secondName: "Пл. Коммунаров", searchName: "Площадь Коммунаров"),
         Transport(link: "https://mobile.ettu.ru/station/3433", nameStation: "Пл. Коммунаров (с ТК Алатырь на Дворец Молодежи)", secondName: "Площадь Коммунаровв", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3670", nameStation: "Пл. Коммунаров (на пл. 1905 г.)", secondName: "Пл. Коммунаров", searchName: "Площадь Коммунаров"),
         Transport(link: "https://mobile.ettu.ru/station/963739", nameStation: "Пл. Коммунаров (на Вечный Огонь)", secondName: "Пл. Коммунаров", searchName: "Площадь Коммунаров"),
         Transport(link: "https://mobile.ettu.ru/station/3434", nameStation: "Пл. Обороны (на Декабристов)", secondName: "Пл. Обороны", searchName: "Площадь Обороны"),
         Transport(link: "https://mobile.ettu.ru/station/3435", nameStation: "Пл. Обороны (на Тверитина)", secondName: "Пл. Обороны", searchName: "Площадь Обороны"),
         Transport(link: "https://mobile.ettu.ru/station/961844", nameStation: "Плотников (со ст. Зеленый остров на ст. ВИЗ)", secondName: "Плотников", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4049", nameStation: "Плотников (на ст. Зеленый остров)", secondName: "Плотников", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4078", nameStation: "Плотников (на Волгоградскую)", secondName: "Плотников", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4079", nameStation: "Плотников (с Волгоградской на Металлургов)", secondName: "Плотников", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961840", nameStation: "Победы (на Индустрии)", secondName: "Победы", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4553", nameStation: "Победы (на Бакинских Комиссаров)", secondName: "Победы", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4252", nameStation: "Посадская (на Цирк, пл. Коммунаров)", secondName: "Посадская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4253", nameStation: "Посадская (на ст. Дворец Спорта)", secondName: "Посадская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3440", nameStation: "Протезно-ортопедическое предприятие (на Челюскинцев)", secondName: "Протезно-ортопедическое предприятие", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3441", nameStation: "Протезно-ортопедическое предприятие (на Шевченко)", secondName: "Протезно-ортопедическое предприятие", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3442", nameStation: "Профессорская (на Гагарина)", secondName: "Профессорская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3443", nameStation: "Профессорская (на Комсомольскую)", secondName: "Профессорская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4050", nameStation: "Рабочих (на ст. Зеленый остров)", secondName: "Рабочих", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4071", nameStation: "Рабочих (на ст. ВИЗ)", secondName: "Рабочих", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3444", nameStation: "Радищева (на Московскую)", secondName: "Радищева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3445", nameStation: "Радищева (на Цирк)", secondName: "Радищева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4052", nameStation: "Разъезд (на ст. Зеленый остров)", secondName: "Разъезд", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4069", nameStation: "Разъезд (на ст. ВИЗ)", secondName: "Разъезд", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4282", nameStation: "Расточная (на ст. 7 Ключей)", secondName: "Расточная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4283", nameStation: "Расточная (на Таганский ряд)", secondName: "Расточная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3448", nameStation: "Сакко и Ванцетти (на пл. Коммунаров)", secondName: "Сакко и Ванцетти", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3449", nameStation: "Сахалинская (на Студенческую)", secondName: "Сахалинская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3450", nameStation: "Сахалинская (на ст. Шарташ)", secondName: "Сахалинская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3451", nameStation: "Сварщиков (на Автомагистральную)", secondName: "Сварщиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3452", nameStation: "Сварщиков (на Лукиных)", secondName: "Сварщиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961845", nameStation: "Серафимы Дерябиной (на ст. ВИЗ)", secondName: "Серафимы Дерябиной", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961846", nameStation: "Серафимы Дерябиной (на Волгоградскую)", secondName: "Серафимы Дерябиной", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3455", nameStation: "Сиреневый б-р (на ст. 40 лет ВЛКСМ)", secondName: "Сиреневый б-р", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3456", nameStation: "Сиреневый б-р (на Новгородцевой)", secondName: "Сиреневый б-р", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3910", nameStation: "Слесарей (на ст. ВИЗ, Кирова)", secondName: "Слесарей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3525", nameStation: "Советская (на Пионерскую)", secondName: "Советская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3539", nameStation: "Советская (на Блюхера)", secondName: "Советская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3457", nameStation: "Студенческая (на ТК Современник)", secondName: "Студенческая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3458", nameStation: "Студенческая (на Сахалинскую)", secondName: "Студенческая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4305", nameStation: "Сухоложская (на ст. Вторчермет, ст. Керамическая)", secondName: "Сухоложская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4306", nameStation: "Сухоложская (на Братскую)", secondName: "Сухоложская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4237", nameStation: "Таганский ряд (со ст. 7 Ключей на Лукиных)", secondName: "Таганский ряд", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4371", nameStation: "Таганский ряд (на ст. 7 Ключей)", secondName: "Таганский ряд", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4372", nameStation: "Таганский ряд (с  ТРЦ Карнавал на Лукиных)", secondName: "Таганский ряд", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4373", nameStation: "Таганский ряд (на ТРЦ Карнавал)", secondName: "Таганский ряд", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3459", nameStation: "Татищева (на Заводскую)", secondName: "Татищева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3460", nameStation: "Татищева (на Волгоградскую, ст. Зеленый остров)", secondName: "Татищева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3947", nameStation: "Тверитина (на ст. ЦПКиО)", secondName: "Тверитина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3955", nameStation: "Тверитина (на Куйбышева-Луначарского)", secondName: "Тверитина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3438", nameStation: "Театр музыкальной комедии (на Оперный театр)", secondName: "Театр муз комедии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3439", nameStation: "Театр музыкальной комедии (на пл. 1905 г.)", secondName: "Театр муз комедии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4270", nameStation: "Теплоходный  пр. (на ст. 7 Ключей)", secondName: "Теплоходный  пр.", searchName: "Теплоходный  проспект"),
         Transport(link: "https://mobile.ettu.ru/station/4271", nameStation: "Теплоходный пр. (на Таганский ряд)", secondName: "Теплоходный  пр.", searchName: "Теплоходный  проспект"),
         Transport(link: "https://mobile.ettu.ru/station/4274", nameStation: "Техническая (на ст. 7 Ключей)", secondName: "Техническая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4277", nameStation: "Техническая (на Таганский ряд)", secondName: "Техническая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3461", nameStation: "Техучилище (на 1-й км)", secondName: "Техучилище", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3462", nameStation: "Техучилище (на Калининскую)", secondName: "Техучилище", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3374", nameStation: "ТК Буревестник (на Волгоградскую)", secondName: "ТК Буревестник", searchName: "Торговый Комплекс Буревестник"),
         Transport(link: "https://mobile.ettu.ru/station/3375", nameStation: "ТК Буревестник (на Московскую)", secondName: "ТК Буревестник", searchName: "Торговый Комплекс Буревестник"),
         Transport(link: "https://mobile.ettu.ru/station/3376", nameStation: "ТК Современник (на Мира)", secondName: "ТК Современник", searchName: "Торговый Комплекс Современник"),
         Transport(link: "https://mobile.ettu.ru/station/961843", nameStation: "ТК Современник (на Студенческую)", secondName: "ТК Современник", searchName: "Торговый Комплекс Современник"),
         Transport(link: "https://mobile.ettu.ru/station/3334", nameStation: "ТРЦ Карнавал (на Верх-Исетский рынок)", secondName: "ТРЦ Карнавал", searchName: "Торгово Развлекательный Центр Карнавал"),
         Transport(link: "https://mobile.ettu.ru/station/3335", nameStation: "ТРЦ Карнавал (на Таганский ряд)", secondName: "ТРЦ Карнавал", searchName: "Торгово Развлекательный Центр Карнавал"),
         Transport(link: "https://mobile.ettu.ru/station/3403", nameStation: "ТЦ Алатырь (на Московскую)", secondName: "ТЦ Алатырь", searchName: "Торговый Центр Алатырь"),
         Transport(link: "https://mobile.ettu.ru/station/3404", nameStation: "ТЦ Алатырь (на пл. Коммунаров)", secondName: "ТЦ Алатырь", searchName: "Торговый Центр Алатырь"),
         Transport(link: "https://mobile.ettu.ru/station/3465", nameStation: "Управление дороги (на Ельцина)", secondName: "Управление дороги", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3466", nameStation: "Управление дороги (на Ж/д вокзал)", secondName: "Управление дороги", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963731", nameStation: "Уралкабель (на Красноуральскую)", secondName: "Уралкабель", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963732", nameStation: "Уралкабель (на Мельникова)", secondName: "Уралкабель", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3463", nameStation: "Уральский федеральный университет (на Восточную)", secondName: "УрФУ", searchName: "УрФУ"),
         Transport(link: "https://mobile.ettu.ru/station/961904", nameStation: "Уральский федеральный университет (на Первомайскую)", secondName: "УрФУ", searchName: "УрФУ"),
         Transport(link: "https://mobile.ettu.ru/station/963284", nameStation: "Уральский федеральный университет (на Профессорскую)", secondName: "УрФУ", searchName: "УрФУ"),
         Transport(link: "https://mobile.ettu.ru/station/4174", nameStation: "Уральских Рабочих (на Бакинских Комиссаров)", secondName: "Уральских Рабочих", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4175", nameStation: "Уральских Рабочих (на Кировградскую)", secondName: "Уральских Рабочих", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4090", nameStation: "Ухтомская (на Серафимы Дерябиной)", secondName: "Ухтомская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4091", nameStation: "Ухтомская (на ст. ВИЗ)", secondName: "Ухтомская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3527", nameStation: "Учителей (на Кондукторскую)", secondName: "Учителей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961841", nameStation: "Учителей (на Блюхера)", secondName: "Учителей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3446", nameStation: "Фармацевтический колледж (на ТРЦ Карнавал)", secondName: "Фармацевтический колледж", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3447", nameStation: "Фармацевтический колледж (на Таганский ряд)", secondName: "Фармацевтический колледж", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4320", nameStation: "Ферганская (на Сухоложскую)", secondName: "Ферганская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4321", nameStation: "Ферганская (на ст. Керамическая)", secondName: "Ферганская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3502", nameStation: "Фрезеровщиков", secondName: "Фрезеровщиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3467", nameStation: "Фронтовых Бригад (на Ворошиловскую)", secondName: "Фронтовых Бригад", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3468", nameStation: "Фронтовых Бригад (на Краснофлотцев)", secondName: "Фронтовых Бригад", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3469", nameStation: "Фрунзе (на Автовокзал)", secondName: "Фрунзе", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3995", nameStation: "Фрунзе (на Большакова)", secondName: "Фрунзе", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963680", nameStation: "Фучика (на Южную, Шварца)", secondName: "Фучика", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963681", nameStation: "Фучика (на б-р Малахова)", secondName: "Фучика", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3472", nameStation: "Цирк (на Белинского)", secondName: "Цирк", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3473", nameStation: "Цирк (на Академию при Президенте России)", secondName: "Цирк", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3474", nameStation: "Цирк (с Белинского на Радищева)", secondName: "Цирк", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3475", nameStation: "Цирк (с Академии при Президенте России на Радищева)", secondName: "Цирк", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3503", nameStation: "ЦПКиО", secondName: "ЦПКиО", searchName: "Центральный парк культуры и отдыха"),
         Transport(link: "https://mobile.ettu.ru/station/3476", nameStation: "Челюскинцев (на Ж/д вокзал, Пионерскую)", secondName: "Челюскинцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3477", nameStation: "Челюскинцев (на Протезно-ортопедическое предприятие)", secondName: "Челюскинцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3504", nameStation: "Шарташ", secondName: "Шарташ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3478", nameStation: "Шарташская (на гост. Исеть)", secondName: "Шарташская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3479", nameStation: "Шарташская (на Шевченко)", secondName: "Шарташская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3330", nameStation: "Шварца (на Ювелирную)", secondName: "Шварца", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3331", nameStation: "Шварца (на Южную, Фучика)", secondName: "Шварца", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3480", nameStation: "Шевченко (на Протезно-ортопедическое предприятие)", secondName: "Шевченко", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3481", nameStation: "Шевченко (на Шарташскую)", secondName: "Шевченко", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3482", nameStation: "Шейнкмана (на Дворец Молодежи)", secondName: "Шейнкмана", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3483", nameStation: "Шейнкмана (на Папанина)", secondName: "Шейнкмана", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4296", nameStation: "Школа им. С.В. Рахманинова (на ст. 7 Ключей)", secondName: "Школа им. С.В. Рахманинова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4297", nameStation: "Школа им. С.В. Рахманинова (на Таганский ряд)", secondName: "Школа им. С.В. Рахманинова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3484", nameStation: "Электриков (на Ворошиловскую)", secondName: "Электриков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3485", nameStation: "Электриков (на Педагогический университет)", secondName: "Электриков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3505", nameStation: "Эльмаш", secondName: "Эльмаш", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3486", nameStation: "Энтузиастов (с Краснофлотцев на ст. Эльмаш, ст. Фрезеровщиков)", secondName: "Энтузиастов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3487", nameStation: "Энтузиастов (со ст. Фрезеровщиков на Краснофлотцев)", secondName: "Энтузиастов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3488", nameStation: "Энтузиастов (со ст. Эльмаш на Краснофлотцев)", secondName: "Энтузиастов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4351", nameStation: "Эскадронная (на ст. Керамическая)", secondName: "Эскадронная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/4352", nameStation: "Эскадронная (на Ляпустина)", secondName: "Эскадронная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3489", nameStation: "Ювелирная (на Шварца)", secondName: "Ювелирная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3490", nameStation: "Ювелирная (на пер. Рижский)", secondName: "Ювелирная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3983", nameStation: "Юго-Западная (на Белореченскую)", secondName: "Юго-Западная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3984", nameStation: "Юго-Западная (на Московскую)", secondName: "Юго-Западная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3491", nameStation: "Южная (на Автовокзал)", secondName: "Южная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3492", nameStation: "Южная (на Шварца, Фучика)", secondName: "Южная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/3496", nameStation: "Южная (конечная)", secondName: "Южная", searchName: nil)]
    
    
    static let dataBus: [Transport] =
        [Transport(link: "https://mobile.ettu.ru/station/962064", nameStation: "1-й км (на Техучилище)", secondName: "1-й км", searchName: "Первый километр"),
         Transport(link: "https://mobile.ettu.ru/station/962097", nameStation: "1-й км (на Ж/д вокзал, Пионерскую)", secondName: "1-й км", searchName: "Первый километр"),
         Transport(link: "https://mobile.ettu.ru/station/962946", nameStation: "40 лет Октября (на Хмелева)", secondName: "40 лет Октября", searchName: "Сорок лет Октября"),
         Transport(link: "https://mobile.ettu.ru/station/961943", nameStation: "Авиационная (на Саввы Белых)", secondName: "Авиационная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962910", nameStation: "Авиационная (на Щорса)", secondName: "Авиационная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962386", nameStation: "Автовокзал (на Серова)", secondName: "Автовокзал", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962435", nameStation: "Автовокзал (на Щорса)", secondName: "Автовокзал", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961914", nameStation: "Азина (на Дом Музыки)", secondName: "Азина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962520", nameStation: "Академгородок", secondName: "Академгородок", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962419", nameStation: "Академика Вонсовского (на Начдива Онуфриева)", secondName: "Академика Вонсовского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962796", nameStation: "Академика Вонсовского (на Рабочую)", secondName: "Академика Вонсовского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962324", nameStation: "Академическая (на Мира)", secondName: "Академическая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962875", nameStation: "Академическая", secondName: "Академическая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962939", nameStation: "Академическая (на ТК Современник)", secondName: "Академическая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962399", nameStation: "Амундсена (на Начдива Онуфриева)", secondName: "Амундсена", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962427", nameStation: "Амундсена (на Волгоградскую)", secondName: "Амундсена", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962790", nameStation: "Амундсена (на пр-д Решетникова)", secondName: "Амундсена", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962010", nameStation: "Артиллерийский институт (на Прониной)", secondName: "Артиллерийский институт", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962806", nameStation: "Артиллерийский институт (на Садовую)", secondName: "Артиллерийский институт", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962045", nameStation: "Архитектурная академия (на ТЮЗ)", secondName: "Архитектурная академия", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961922", nameStation: "Архитектурная академия (на пр. Ленина)", secondName: "Архитектурная академия", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962618", nameStation: "Бакинских Комиссаров (на Ломоносова)", secondName: "Бакинских Комиссаров", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962988", nameStation: "Бакинских Комиссаров (на ст. Коммунистическая)", secondName: "Бакинских Комиссаров", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962696", nameStation: "Баумана (на Красных Командиров)", secondName: "Баумана", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962372", nameStation: "Белореченская (на ст. Посадская)", secondName: "Белореченская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962376", nameStation: "Белореченская (на Гурзуфскую)", secondName: "Белореченская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962653", nameStation: "Библиотека (на Краснознаменную)", secondName: "Библиотека", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962794", nameStation: "Библиотека им. Белинского (на Дом Кино, пр. Ленина)", secondName: "Библиотека им. Белинского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962832", nameStation: "Библиотека им. Крапивина (на Советскую)", secondName: "Библиотека им. Крапивина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962833", nameStation: "Библиотека им. Крапивина (на Луначарского)", secondName: "Библиотека им. Крапивина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962793", nameStation: "Большакова (на Декабристов)", secondName: "Большакова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962134", nameStation: "Боровая (на ТК Современник)", secondName: "Боровая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962337", nameStation: "Боровая (на Менделеева)", secondName: "Боровая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961979", nameStation: "Бородина (на Инженерную)", secondName: "Боровая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961994", nameStation: "Бородина (на ДК Химмаш)", secondName: "Боровая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962475", nameStation: "Ботаническая", secondName: "Ботаническая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962638", nameStation: "Б-р Культуры (на пр. Орджоникидзе)", secondName: "Б-р Культуры", searchName: "Бульвар Культуры"),
         Transport(link: "https://mobile.ettu.ru/station/962472", nameStation: "Б-р Малахова (на ст. Ботаническая)", secondName: "Б-р Малахова", searchName: "Бульвар Малахова"),
         Transport(link: "https://mobile.ettu.ru/station/962479", nameStation: "Б-р Малахова (на Тбилисский б-р)", secondName: "Б-р Малахова", searchName: "Бульвар Малахова"),
         Transport(link: "https://mobile.ettu.ru/station/962581", nameStation: "Веер (на Ломоносова)", secondName: "Веер", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962942", nameStation: "Веер (на Ярославскую)", secondName: "Веер", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962202", nameStation: "Викулова (на Крауля)", secondName: "Викулова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962218", nameStation: "Викулова (на Заводскую)", secondName: "Викулова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962739", nameStation: "Войкова (на Красных Командиров)", secondName: "Войкова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962395", nameStation: "Волгоградская (на Амундсена)", secondName: "Волгоградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962792", nameStation: "Волгоградская (на Шаумяна)", secondName: "Волгоградская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962707", nameStation: "Ворошиловская (на Фронтовых Бригад)", secondName: "Ворошиловская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962721", nameStation: "Ворошиловская (на Электриков)", secondName: "Ворошиловская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962659", nameStation: "Восстания (на Стахановскую)", secondName: "Восстания", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962943", nameStation: "Восстания (на Ломоносова)", secondName: "Восстания", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962944", nameStation: "Восстания (на Победы)", secondName: "Восстания", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962156", nameStation: "Гагарина (на Генеральскую)", secondName: "Гагарина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962309", nameStation: "Гагарина (на Профессорскую)", secondName: "Гагарина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962152", nameStation: "Генеральская (на Трансагентство)", secondName: "Генеральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962927", nameStation: "Генеральская (на Гагарина)", secondName: "Генеральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962803", nameStation: "Гончарный (на Уктус)", secondName: "Гончарный", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962175", nameStation: "Горького (на Храм Большой Златоуст)", secondName: "Горького", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962367", nameStation: "Гурзуфская (на Белореченскую)", secondName: "Гурзуфская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962380", nameStation: "Гурзуфская (на Репина)", secondName: "Гурзуфская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961985", nameStation: "Дагестанская (на ст. Химмаш)", secondName: "Дагестанская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962335", nameStation: "Данилы Зверева (на Боровую)", secondName: "Данилы Зверева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962033", nameStation: "Декабристов (на Куйбышева)", secondName: "Декабристов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962795", nameStation: "Декабристов (с Большакова на Чапаева)", secondName: "Декабристов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962631", nameStation: "Детская больница (на пл. 1-й Пятилетки)", secondName: "Детская больница", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962897", nameStation: "Димитрова (на Косарева)", secondName: "Димитрова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962053", nameStation: "ДК железнодорожников (на ст. Ж/д вокзал, ст. Академическая, ст. Коммунистическая)", secondName: "ДК железнодорожников", searchName: "Дворец Культуры железнодорожников"),
         Transport(link: "https://mobile.ettu.ru/station/962550", nameStation: "ДК им. Лаврова (на Фрезеровщиков)", secondName: "ДК им. Лаврова", searchName: "Дворец Культуры им. Лаврова"),
         Transport(link: "https://mobile.ettu.ru/station/962596", nameStation: "ДК им. Лаврова (на м. Уралмаш)", secondName: "ДК им. Лаврова", searchName: "Дворец Культуры им. Лаврова"),
         Transport(link: "https://mobile.ettu.ru/station/962898", nameStation: "ДК Химмаш (на Бородина)", secondName: "ДК Химмаш", searchName: "Дворец Культуры Химмаш"),
         Transport(link: "https://mobile.ettu.ru/station/962900", nameStation: "ДК Химмаш (на Димитрова)", secondName: "ДК Химмаш", searchName: "Дворец Культуры Химмаш"),
         Transport(link: "https://mobile.ettu.ru/station/962149", nameStation: "Дом Кино (на Горького, ст. Ж/д вокзал, ст. Химмаш)", secondName: "Дом Кино", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962292", nameStation: "Дом Кино (на Трансагентство)", secondName: "Дом Кино", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962114", nameStation: "Дом Музыки (на ДК железнодорожников)", secondName: "Дом Музыки", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961915", nameStation: "Дом Музыки (на ТЮЗ)", secondName: "Дом Музыки", searchName: "Дом Музыки"),
         Transport(link: "https://mobile.ettu.ru/station/962647", nameStation: "Дом Пионеров (на пр. Орджоникидзе)", secondName: "Дом Пионеров", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962062", nameStation: "Ж/д вокзал (на Азина)", secondName: "Ж/д вокзал", searchName: "Жд вокзал"),
         Transport(link: "https://mobile.ettu.ru/station/961905", nameStation: "Ж/д вокзал (1, 9 маршруты)", secondName: "Ж/д вокзал", searchName: "Жд вокзал"),
         Transport(link: "https://mobile.ettu.ru/station/962867", nameStation: "Ж/д вокзал (11 маршрут)", secondName: "Ж/д вокзал", searchName: "Жд вокзал"),
         Transport(link: "https://mobile.ettu.ru/station/962200", nameStation: "Заводская (на Викулова)", secondName: "Заводская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962220", nameStation: "Заводская (на Токарей)", secondName: "Заводская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962690", nameStation: "Ильича (на м. пр. Космонавтов)", secondName: "Ильича", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962691", nameStation: "Ильича", secondName: "Ильича", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962556", nameStation: "Индустрии (на Ломоносова)", secondName: "Индустрии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962588", nameStation: "Индустрии (на Фрезеровщиков)", secondName: "Индустрии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962658", nameStation: "Индустрии (на Ильича)", secondName: "Индустрии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961970", nameStation: "Инженера Алиева (на Димитрова)", secondName: "Инженера Алиева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962901", nameStation: "Инженера Алиева (на Нижнеисетск)", secondName: "Инженера Алиева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961982", nameStation: "Инженерная (на Дагестанскую)", secondName: "Инженерная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962899", nameStation: "Инженерная (на Бородина)", secondName: "Инженерная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962018", nameStation: "Институт дерматологии (на Самолетную)", secondName: "Институт дерматологии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962802", nameStation: "Институт дерматологии (на Гончарный)", secondName: "Институт дерматологии", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962196", nameStation: "Институт связи (на Токарей)", secondName: "Институт связи", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962234", nameStation: "Институт связи (на Центральный стадион)", secondName: "Институт связи", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963003", nameStation: "Институт связи (на Гурзуфскую)", secondName: "Институт связи", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962840", nameStation: "Июльская (на Парковый пер.)", secondName: "Июльская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962921", nameStation: "Июльская (на ст. Сулимова)", secondName: "Июльская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962613", nameStation: "Калинина (на Победы)", secondName: "Калинина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962627", nameStation: "Калинина (на Детскую больницу)", secondName: "Калинина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962067", nameStation: "Калининская (на Педагогический университет)", secondName: "Калининская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962093", nameStation: "Калининская (на Техучилище)", secondName: "Калининская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963778", nameStation: "Каменный ручей (на Прониной)", secondName: "Каменный ручей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962092", nameStation: "Карла Маркса (на Библиотеку им. Белинского)", secondName: "Карла Маркса", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962501", nameStation: "Кварцевая (на ст. Табачная фабрика Альвис)", secondName: "Кварцевая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962512", nameStation: "Кварцевая (на Павлодарскую)", secondName: "Кварцевая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963024", nameStation: "Коммунистическая", secondName: "Коммунистическая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961976", nameStation: "Косарева (на ДК Химмаш)", secondName: "Косарева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962651", nameStation: "Краснознаменная (на пл. 1-й Пятилетки)", secondName: "Краснознаменная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962072", nameStation: "Краснофлотцев (с Педагогического университета на м. Уралмаш)", secondName: "Краснофлотцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962703", nameStation: "Краснофлотцев (на Краснофлотцев)", secondName: "Краснофлотцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962726", nameStation: "Краснофлотцев (на Фронтовых Бригад)", secondName: "Краснофлотцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962742", nameStation: "Краснофлотцев (на Шефскую)", secondName: "Краснофлотцев", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962693", nameStation: "Красных Командиров (на ст. Таганская)", secondName: "Красных Командиров", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962737", nameStation: "Красных Командиров (на Спортивную)", secondName: "Красных Командиров", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962207", nameStation: "Крауля (на ст. Крауля)", secondName: "Крауля", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962208", nameStation: "Крауля", secondName: "Крауля", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/963009", nameStation: "Крауля (на ст.Крауля(по требованию)", secondName: "Крауля", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962911", nameStation: "Крестинского (на Родонитовую)", secondName: "Крестинского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962912", nameStation: "Крестинского (на Шварца)", secondName: "Крестинского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962034", nameStation: "Куйбышева (на Карла Маркса)", secondName: "Куйбышева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961931", nameStation: "Куйбышева (на Декабристов)", secondName: "Куйбышева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962417", nameStation: "Лесная (на Рабочую)", secondName: "Лесная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962797", nameStation: "Лесная (на ТК Академический)", secondName: "Лесная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962557", nameStation: "Ломоносова (на Веер)", secondName: "Ломоносова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962584", nameStation: "Ломоносова (на Индустрии)", secondName: "Ломоносова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962607", nameStation: "Ломоносова (на Бакинских Комиссаров)", secondName: "Ломоносова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962621", nameStation: "Ломоносова (на Восстания)", secondName: "Ломоносова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962827", nameStation: "Луначарского (на ТЮЗ)", secondName: "Луначарского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962920", nameStation: "Луначарского (на Библиотеку им. Крапивина)", secondName: "Луначарского", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962818", nameStation: "Метро Динамо (на ТЮЗ)", secondName: "М. Динамо", searchName: "Динамо"),
         Transport(link: "https://mobile.ettu.ru/station/962919", nameStation: "Метро Динамо", secondName: "М. Динамо", searchName: "Динамо"),
         Transport(link: "https://mobile.ettu.ru/station/962668", nameStation: "Метро пр. Космонавтов (на Стахановскую)", secondName: "М. пр. Космонавтов", searchName: "Проскпект Космонавтов"),
         Transport(link: "https://mobile.ettu.ru/station/962687", nameStation: "Метро пр. Космонавтов (на Старых Большевиков)", secondName: "М. пр. Космонавтов", searchName: "Проскпект Космонавтов"),
         Transport(link: "https://mobile.ettu.ru/station/962076", nameStation: "Метро Уралмаш (на ст. пл. 1-й Пятилетки)", secondName: "М. Уралмаш", searchName: "Уралмаш"),
         Transport(link: "https://mobile.ettu.ru/station/962088", nameStation: "Метро Уралмаш (на Педагогический университет)", secondName: "М. Уралмаш", searchName: "Уралмаш"),
         Transport(link: "https://mobile.ettu.ru/station/962548", nameStation: "Метро Уралмаш (на ДК им. Лаврова)", secondName: "М. Уралмаш", searchName: "Уралмаш"),
         Transport(link: "https://mobile.ettu.ru/station/962492", nameStation: "Межевая (на Павлодарскую)", secondName: "Межевая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962131", nameStation: "Менделеева (на Боровую)", secondName: "Менделеева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962339", nameStation: "Менделеева (на Парк Хаус)", secondName: "Менделеева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962414", nameStation: "Микрорайон (на ТК Академический)", secondName: "Микрорайон", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962995", nameStation: "Микрорайон (на ст. Академгородок)", secondName: "Микрорайон", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962934", nameStation: "Мира (на Уральский федеральный университет, Софьи Ковалевской)", secondName: "Мира", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962785", nameStation: "Музей Бажова (на Трамвайный парк)", secondName: "Музей Бажова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962401", nameStation: "Начдива Онуфриева (на Академика Вонсовского)", secondName: "Начдива Онуфриева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962425", nameStation: "Начдива Онуфриева (на Амундсена)", secondName: "Начдива Онуфриева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962456", nameStation: "Начдива Онуфриева (на Чкалова)", secondName: "Начдива Онуфриева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962461", nameStation: "Начдива Онуфриева", secondName: "Начдива Онуфриева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961969", nameStation: "Нижнеисетск (на Инженера Алиева)", secondName: "Нижнеисетск", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962902", nameStation: "Нижнеисетск (на Опытную станцию садоводства)", secondName: "Нижнеисетск", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961965", nameStation: "Опытная станция садоводства (на Нижнеисетск)", secondName: "Опытная станция садоводства", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962903", nameStation: "Опытная станция садоводства (на Садовую)", secondName: "Опытная станция садоводства", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962493", nameStation: "Павлодарская (на Кварцевую)", secondName: "Павлодарская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962513", nameStation: "Павлодарская (на Самолетную)", secondName: "Павлодарская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962130", nameStation: "Парк Хаус (на Менделеева)", secondName: "Парк Хаус", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962343", nameStation: "Парк Хаус (на Уральскую)", secondName: "Парк Хаус", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962453", nameStation: "Парк Чкалова (на ст. Начдива Онуфриева)", secondName: "Парк Чкалова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962001", nameStation: "Пархоменко (на Инженера Алиева)", secondName: "Пархоменко", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962746", nameStation: "Педагогический университет", secondName: "Педагогический университет", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962940", nameStation: "Педагогический университет (на Краснофлотцев)", secondName: "Педагогический университет", searchName: "Пед университет"),
         Transport(link: "https://mobile.ettu.ru/station/962941", nameStation: "Педагогический университет (на Калининскую)", secondName: "Педагогический университет", searchName: "Пед университет"),
         Transport(link: "https://mobile.ettu.ru/station/962837", nameStation: "Пер. Парковый (на Июльскую)", secondName: "Пер. Парковый ", searchName: "Переулок Парковый"),
         Transport(link: "https://mobile.ettu.ru/station/962841", nameStation: "Пер. Парковый (на Советскую)", secondName: "Пер. Парковый ", searchName: "Переулок Парковый"),
         Transport(link: "https://mobile.ettu.ru/station/962016", nameStation: "Пер. Широкий (на Институт дерматологии)", secondName: "Пер. Широкий", searchName: "Переулок Широкий"),
         Transport(link: "https://mobile.ettu.ru/station/962932", nameStation: "Первомайская (на Студенческую)", secondName: "Первомайская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962124", nameStation: "Пионерская (на Уральскую)", secondName: "Пионерская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962350", nameStation: "Пионерская (на Ж/д вокзал, 1-й км)", secondName: "Пионерская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962080", nameStation: "Пл. 1-й Пятилетки", secondName: "Пл. 1-й Пятилетки", searchName: "Площадь первой Пятилетки"),
         Transport(link: "https://mobile.ettu.ru/station/962881", nameStation: "Пл. 1-й Пятилетки (на Дом Пионеров)", secondName: "Пл. 1-й Пятилетки", searchName: "Площадь первой Пятилетки"),
         Transport(link: "https://mobile.ettu.ru/station/962882", nameStation: "Пл. 1-й Пятилетки (на Церковь Рождества Христова)", secondName: "Пл. 1-й Пятилетки", searchName: "Площадь первой Пятилетки"),
         Transport(link: "https://mobile.ettu.ru/station/962611", nameStation: "Победы (на Восстания)", secondName: "Победы", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962626", nameStation: "Победы (на Калинина)", secondName: "Победы", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962374", nameStation: "Посадская", secondName: "Посадская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961924", nameStation: "Пр. Ленина (на Горького, Центральную гост.)", secondName: "Пр. Ленина", searchName: "Проспект Ленина"),
         Transport(link: "https://mobile.ettu.ru/station/962782", nameStation: "Пр. Ленина (на Архитектурную академию)", secondName: "Пр. Ленина", searchName: "Проспект Ленина"),
         Transport(link: "https://mobile.ettu.ru/station/962640", nameStation: "Пр. Орджоникидзе (на Калинина 8 м-т)", secondName: "Пр. Орджоникидзе", searchName: "Проспект Орджоникидзе"),
         Transport(link: "https://mobile.ettu.ru/station/962649", nameStation: "Пр. Орджоникидзе (на Калинина 10 м-т)", secondName: "Пр. Орджоникидзе", searchName: "Проспект Орджоникидзе"),
         Transport(link: "https://mobile.ettu.ru/station/962446", nameStation: "Пр-д Решетникова (на Чкалова)", secondName: "Пр-д Решетникова", searchName: "Проезд Решетникова"),
         Transport(link: "https://mobile.ettu.ru/station/962462", nameStation: "Пр-д Решетникова (на Амундсена)", secondName: "Пр-д Решетникова", searchName: "Проезд Решетникова"),
         Transport(link: "https://mobile.ettu.ru/station/962805", nameStation: "Прониной (на Артиллерийский институт)", secondName: "Прониной", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962905", nameStation: "Прониной (на Уктус)", secondName: "Прониной", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962158", nameStation: "Профессорская (на Гагарина)", secondName: "Профессорская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962313", nameStation: "Профессорская (на Уральский федеральный университет)", secondName: "Профессорская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962407", nameStation: "Рабочая (на Лесную)", secondName: "Рабочая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962418", nameStation: "Рабочая (на Академика Вонсовского)", secondName: "Рабочая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962233", nameStation: "Репина (на Институт связи)", secondName: "Репина", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962470", nameStation: "Родонитовая (на Тбилисский б-р)", secondName: "Родонитовая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962482", nameStation: "Родонитовая (на Крестинского)", secondName: "Родонитовая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962454", nameStation: "Рынок на Громова (на ст. Начдива Онуфриева)", secondName: "Рынок на Громова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962024", nameStation: "Саввы Белых (на Авиационную)", secondName: "Саввы Белых", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962800", nameStation: "Саввы Белых (на ст. Химмаш, ст. Ботаническая)", secondName: "Саввы Белых", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961963", nameStation: "Садовая (на Опытную станцию садоводства)", secondName: "Садовая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962904", nameStation: "Садовая (на Артиллерийский институт)", secondName: "Садовая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962020", nameStation: "Самолетная (на Шварца)", secondName: "Самолетная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962490", nameStation: "Самолетная (на Межевую)", secondName: "Самолетная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962496", nameStation: "Самолетная (с Павлодарской на Самолетную)", secondName: "Самолетная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962801", nameStation: "Самолетная (на Институт дерматологии)", secondName: "Самолетная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962432", nameStation: "Серова (на Автовокзал)", secondName: "Серова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962789", nameStation: "Серова (на Шаумяна)", secondName: "Серова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962834", nameStation: "Советская (на пер. Парковый)", secondName: "Советская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962842", nameStation: "Советская (на Библиотеку им. Крапивина)", secondName: "Советская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962323", nameStation: "Софьи Ковалевской (на Первомайскую)", secondName: "Софьи Ковалевской", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962699", nameStation: "Спортивная (на Баумана)", secondName: "Спортивная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962734", nameStation: "Спортивная (на Шефскую)", secondName: "Спортивная", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962684", nameStation: "Старых Большевиков (на Шефскую)", secondName: "Старых Большевиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962665", nameStation: "Стахановская (на Восстания)", secondName: "Стахановская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962933", nameStation: "Студенческая (на ст. Академическая)", secondName: "Студенческая", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962922", nameStation: "Сулимова", secondName: "Сулимова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962515", nameStation: "Табачная фабрика", secondName: "Табачная фабрика", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962677", nameStation: "Таганская (на Шефскую)", secondName: "Таганская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962749", nameStation: "Таганская", secondName: "Таганская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962471", nameStation: "Тбилисский б-р (на б-р Малахова)", secondName: "Тбилисский б-р", searchName: "Тбилисский бульвар"),
         Transport(link: "https://mobile.ettu.ru/station/962481", nameStation: "Тбилисский б-р (на Родонитовую)", secondName: "Тбилисский б-р", searchName: "Тбилисский бульвар"),
         Transport(link: "https://mobile.ettu.ru/station/962181", nameStation: "Театр Волхонка (на ТЦ Алатырь)", secondName: "Театр Волхонка", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962244", nameStation: "Театр Волхонка (на Храм Большой Златоуст)", secondName: "Театр Волхонка", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962066", nameStation: "Техучилище (на Калининскую)", secondName: "Техучилище", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962095", nameStation: "Техучилище (на 1-й км)", secondName: "Техучилище", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962410", nameStation: "ТК Академический (на ст. Академгородок)", secondName: "ТК Академический", searchName: "Торговый Комплекс Академический"),
         Transport(link: "https://mobile.ettu.ru/station/962416", nameStation: "ТК Академический (на Лесную)", secondName: "ТК Академический", searchName: "Торговый Комплекс Академический"),
         Transport(link: "https://mobile.ettu.ru/station/962138", nameStation: "ТК Современник (на Академическую)", secondName: "ТК Современник", searchName: "Торговый Комплекс Современник"),
         Transport(link: "https://mobile.ettu.ru/station/962333", nameStation: "ТК Современник (на Данилы Зверева)", secondName: "ТК Современник", searchName: "Торговый Комплекс Современник"),
         Transport(link: "https://mobile.ettu.ru/station/962198", nameStation: "Токарей (на Заводскую)", secondName: "Токарей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962224", nameStation: "Токарей (на Институт связи)", secondName: "Токарей", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962110", nameStation: "Трамвайный парк (на Фрунзе)", secondName: "Трамвайный парк", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962150", nameStation: "Трансагентство (на Дом Кино)", secondName: "Трансагентство", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962305", nameStation: "Трансагентство (на Генеральскую)", secondName: "Трансагентство", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962183", nameStation: "ТЦ Алатырь (на Центральный стадион)", secondName: "ТЦ Алатырь", searchName: "Торговый Центр Алатырь"),
         Transport(link: "https://mobile.ettu.ru/station/962242", nameStation: "ТЦ Алатырь (на Театр Волхонка)", secondName: "ТЦ Алатырь", searchName: "Торговый Центр Алатырь"),
         Transport(link: "https://mobile.ettu.ru/station/962047", nameStation: "ТЮЗ (с Архитектурной академии на Дом Музыки)", secondName: "ТЮЗ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961920", nameStation: "ТЮЗ (на Архитектурную академию)", secondName: "ТЮЗ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962808", nameStation: "ТЮЗ (на ст. м. Динамо)", secondName: "ТЮЗ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962822", nameStation: "ТЮЗ (со ст. м. Динамо на Луначарского)", secondName: "ТЮЗ", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962015", nameStation: "Уктус (на Гончарный)", secondName: "Уктус", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961956", nameStation: "Уктус (на Каменный ручей)", secondName: "Уктус", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962848", nameStation: "Уктус", secondName: "Уктус", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962126", nameStation: "Уральская (на Парк Хаус)", secondName: "Уральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962347", nameStation: "Уральская (на Пионерскую)", secondName: "Уральская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962173", nameStation: "Уральский федеральный университет (на Профессорскую)", secondName: "УрФУ", searchName: "УрФУ"),
         Transport(link: "https://mobile.ettu.ru/station/962314", nameStation: "Уральский федеральный университет (на Софьи Ковалевской)", secondName: "УрФУ", searchName: "УрФУ"),
         Transport(link: "https://mobile.ettu.ru/station/961928", nameStation: "Федерация профсоюзов (на Куйбышева)", secondName: "Федерация профсоюзов", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962553", nameStation: "Фрезеровщиков (на Индустрии)", secondName: "Фрезеровщиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962592", nameStation: "Фрезеровщиков (на ДК им. Лаврова)", secondName: "Фрезеровщиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962671", nameStation: "Фрезеровщиков (с Шефской на м. пр. Космонавтов)", secondName: "Фрезеровщиков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962704", nameStation: "Фронтовых Бригад (на Краснофлотцев)", secondName: "Фронтовых Бригад", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962722", nameStation: "Фронтовых Бригад (на Ворошиловскую)", secondName: "Фронтовых Бригад", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962786", nameStation: "Фрунзе (на Щорса)", secondName: "Фрунзе", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962998", nameStation: "Фрунзе (на Большакова)", secondName: "Фрунзе", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961989", nameStation: "Химмаш", secondName: "Химмаш", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962945", nameStation: "Хмелева (на б-р Культуры)", secondName: "Хмелева", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962178", nameStation: "Храм Большой Златоуст (на Театр Волхонка)", secondName: "Храм Большой Златоуст", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962247", nameStation: "Храм Большой Златоуст (на Центральную гост.)", secondName: "Храм Большой Златоуст", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962251", nameStation: "Центральная гост. (на пр. Ленина, Дом Кино)", secondName: "Центральная гост.", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962294", nameStation: "Центральная гост. (на Федерацию профсоюзов, Библиотеку им. Белинского)", secondName: "Центральная гост.", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962188", nameStation: "Центральный стадион (на Институт связи)", secondName: "Центральный стадион", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962236", nameStation: "Центральный стадион (на ТЦ Алатырь)", secondName: "Центральный стадион", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962635", nameStation: "Церковь Рождества Христова (на 40 лет Октября)", secondName: "Церковь Рождества Христова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962442", nameStation: "ЦПКиО", secondName: "ЦПКиО", searchName: "Центральный Парк Культуры и Отдыха"),
         Transport(link: "https://mobile.ettu.ru/station/962784", nameStation: "Чапаева (на Музей Бажова)", secondName: "Чкалова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962452", nameStation: "Чкалова (на парк Чкалова)", secondName: "Чкалова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962791", nameStation: "Чкалова (на пр-д Решетникова)", secondName: "Чкалова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962392", nameStation: "Шаумяна (на Волгоградскую)", secondName: "Шаумяна", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962431", nameStation: "Шаумяна (на Серова)", secondName: "Шаумяна", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/961948", nameStation: "Шварца (на Самолетную)", secondName: "Шварца", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962909", nameStation: "Шварца (на Саввы Белых)", secondName: "Шварца", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962674", nameStation: "Шефская (с Таганской на Фрезеровщиков)", secondName: "Шефская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962683", nameStation: "Шефская (со Старых Большевиков на ст. Таганская)", secondName: "Шефская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962700", nameStation: "Шефская (с Краснофлотцев на Спортивную)", secondName: "Шефская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962730", nameStation: "Шефская (со Спортивной на Краснофлотцев)", secondName: "Шефская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962655", nameStation: "Школа (на Библиотеку)", secondName: "Школа", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962908", nameStation: "Щербакова (на ТРЦ Екатерининский)", secondName: "Щербакова", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962768", nameStation: "Щорса (на Авиационную)", secondName: "Щорса", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962771", nameStation: "Щорса (на Фрунзе)", secondName: "Щорса", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962788", nameStation: "Щорса (на Автовокзал)", secondName: "Щорса", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962799", nameStation: "Щорса (на ст. ЦПКиО)", secondName: "Щорса", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962710", nameStation: "Электриков (на Ворошиловскую)", secondName: "Электриков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962718", nameStation: "Электриков (на ст. Педагогический университет)", secondName: "Электриков", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962504", nameStation: "Южный пр. (на ст. Табачная фабрика)", secondName: "Южный пр.", searchName: "Южный проспект"),
         Transport(link: "https://mobile.ettu.ru/station/962526", nameStation: "Южный пр. (на Кварцевую)", secondName: "Южный пр.", searchName: "Южный проспект"),
         Transport(link: "https://mobile.ettu.ru/station/962563", nameStation: "Ярославская (на ст. Коммунистическая)", secondName: "Ярославская", searchName: nil),
         Transport(link: "https://mobile.ettu.ru/station/962578", nameStation: "Ярославская (на Веер)", secondName: "Ярославская", searchName: nil)]
    
    
}
